[package]
name = "exmex"
version = "0.4.0"  # check html document root in lib.rs and the Readme.md
authors = ["Behrang Shafei <https://github.com/bertiqwerty>"]
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/exmex"
description = "Exmex is an EXtendable Mathematical EXpression evaluator. Users can define their own operators and work with non-float data."
repository = "https://github.com/bertiqwerty/exmex/"
homepage = "https://github.com/bertiqwerty/exmex/"
readme = "README.md"
keywords = ["math", "parser", "expression", "eval", "formula"]
categories = ["parser-implementations"]
include = ["**/*.rs", "Cargo.toml"]

[dependencies]
regex = "1"
num = "0.4"
itertools = "0.10.1"

 