[package]
name = "exexpress"
version = "0.2.0"
authors = ["Behrang Shafei <https://github.com/bertiqwerty>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
num = "0.4"
itertools = "0.10.1"
 