[package]
name = "evilexpress"
version = "0.1.0"
authors = ["Behrang Shafei <https://github.com/bertiqwerty>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
lazy_static = "1.4.0"
num = "0.4"
simple-error = "0.2.3"
itertools = "0.8"