[package]
name = "exmex"
version = "0.2.0"
authors = ["Behrang Shafei <https://github.com/bertiqwerty>"]
edition = "2018"
license = "MIT"
description = "Exmex parses and evaluates mathematical expressions. Users can define their own operators and work with non-float data."
repository = "https://github.com/bertiqwerty/exmex/"
readme = "README.md"
keywords = ["math", "parse", "parser", "mathematical", "expression", "eval", "evaluator", "formula"]

[dependencies]
regex = "1"
num = "0.4"
itertools = "0.10.1"
 