[package]
name = "exexpress"
version = "0.2.0"
authors = ["Behrang Shafei <https://github.com/bertiqwerty>"]
edition = "2018"
license = "MIT"
description = "Exexpress parses and evaluates mathematical expressions. Thereby, library users can define their own unary and binary operators."
repository = "https://github.com/bertiqwerty/exexpress/"
readme = "README.md"
keywords = ["math", "parse", "parser", "mathematical", "expression", "eval", "evaluator", "formula"]

[dependencies]
regex = "1"
num = "0.4"
itertools = "0.10.1"
 